### ISSUE TITLE
subgrids

### ISSUE THREAD

**Issue by manumaticx** [prodz18/TiFlexiGrid#10]
Would you think, that it could be possible to create sub-grids within grid items to create an even more flexible grid? Something like [FreeFlow](https://github.com/Comcast/FreeFlow)

Without changing the aspect ratio it would be possible to combine four small grid items within one item. Then you could have a 1-4-4-1-1-4-4-1-1-etc. grid.

I'll try to test this with your widget and let you know.

**Comment by prodz18** [comment]
Actually, you can achieve this right now. Each item can now have it's own independent layout. So, you could create a grid like FreeFlow easily. I'll try to post a sample later.
