### ISSUE TITLE
Titanium Module

### ISSUE THREAD

**Issue by deckameron** [prodz18/TiFlexiGrid#13]
Pablo,

Are you planning on releasing a module version of your widget?

Thanks,

**Comment by prodz18** [comment]
Hi. Yes. I've been pretty busy lately, but I will release TiFlexiGrid and TiDynamicGrid as Common-JS modules as soon as I can (maybe in a week or two).

**Comment by deckameron** [comment]
@pablorr18 that would be awesome. Thank you!

**Comment by caspahouzer** [comment]
Hi. Are there any news for that?

**Comment by prodz18** [comment]
Hi Everyone! I just uploaded the module version of TiFlexiGrid.
