### ISSUE TITLE
Thumbnails not Generating

### ISSUE THREAD

**Issue by mischacolley** [prodz18/TiFlexiGrid#4]
I've got your widget integrated with my project. Its exactly what I have been looking for but unfortunately I am having issues with the thumbnails not displaying. They seem to be intermittent and  only show sometimes. Actually only once when I had showTitle set to true. I'm using the gallery layout and iOS simulator for testing. I haven't tried it on a device yet. Any thoughts?

**Comment by masterbee** [comment]
@pablorr18 - Same here for as well. Actually all thumbs are not showing at all

**Comment by prodz18** [comment]
I'll look into this.

**Comment by prodz18** [comment]
Fixed in update 1.2
