### ISSUE TITLE
How to get the image source upon on click (and edit pop up)

### ISSUE THREAD

**Issue by darkhorse2013** [prodz18/TiFlexiGrid#8]
Great widget, however I have the following questions Pablo - I followed your docs and created a grid. What I would love to do is after you click on the image:

1) after the pop up opens up, put a button in the pop up - if they click on the button, I can then get the URL for the image (I am fetching images remotely) and set it as their profile picture?

How can I do this?

2) In the window, instead of:

```
<Window id="win">
<View id="fgHeader">    
        <Button id="btnRight" onClick="rightButtonClicked" />
</View>
```

I would like to do this:

```
<Window id="win">   
     <RightNavButton> 
        <Button id="btnRight" onClick="rightButtonClicked" />
</RightNavButton> 
```

How can I do this?

Thanks

**Comment by prodz18** [comment]
I just updated the widget to 1.2. Check out the documentation and the sample app included for example.
