### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by darkhorse2013** [prodz18/TiFlexiGrid#9]
I have got your widget working, however there is a bug.

When I load up the widget for the first time, the thumbnails are not loaded - to view them, I will have to leave the window and return again.

This tends to happen a lot if I fetch the images from a  http url.

**Comment by fishnyc22** [comment]
Love this widget Thanks!. But I have the same issue just came over looking for a fix.

**Comment by prodz18** [comment]
Hi! I'm currently working on a new version of TiFlexigrid and this is one of the issues that will be fixed, among others.

**Comment by prodz18** [comment]
Fixed in update 1.2.
